language: python

python:
 - 3.7
 - 3.8

env:
 - DJANGO=3.0
 - DJANGO=master

matrix:
  include:
    - python: 3.7
      env: TOXENV=isort
    - python: 3.7
      env: TOXENV=flake8

  allow_failures:
    - env: DJANGO=master

install: pip install tox-travis codecov
script: tox
after_success: codecov
